sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache
    - $HOME/.wp-cli/cache
    - $HOME/.wp-cli/packages/cache

language:
  - php
  - node_js

branches:
  only:
    - /^v\d.*$/
    - master
    - develop

env:
  global:
    - WP_THEME=lyrical

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar > /tmp/wp-cli.phar
  - chmod +x /tmp/wp-cli.phar

script:
  - echo "Deploy only"

before_deploy:
  - mkdir -p /tmp/$WP_THEME
  - rsync -av --exclude-from $TRAVIS_BUILD_DIR/.distignore --delete $TRAVIS_BUILD_DIR/ /tmp/$WP_THEME/
  - cd /tmp
  - zip -rT $TRAVIS_BUILD_DIR/$WP_THEME.zip $WP_THEME/
  - sha256sum -b $TRAVIS_BUILD_DIR/$WP_THEME.zip | awk '{print $1}' | tee $TRAVIS_BUILD_DIR/$WP_THEME.zip.sha256

deploy:
  provider: releases
  api_key:
    secure: fFmoQadLqF9Ak+gY6aXBvU5vThT0bBW65qGhTWyULhQqBfJa+AT20wW3gSZlvZ14BJOZK69Hgi8KqyO1nGC6NFuSscB/J4DWJQBp5mhaK5jTstXlnpSIEsqfZDas2xrcCwCdRB8HdNP9M0ZxGUuNFNjDga4Zt0TUMVT51pZTjk7eNbLj7c3flaOUCu56KtRtPMuQvJWd7h9h7DpLkgDgBLWMd9ABXlzXQbGCH09aLieMBbPE4Uqgq8YEnV/OlUVbqLNZlGrQCQSEyuhZceD30G+7B13e85CDFExSWUMgOO+lk7JnEhLPQX1WNwJxa5QeC7pKTSE8Ct2Ndldkmo0HCA7DTOx6gjWkzC5DGNy0dADJ3VV39m8RyYc2OGJr91uHJ1hr1sB2EOsRPLIGe6ZpOHxlS+JXh48CU7eNqfrSLIDuD7teagUis7ZNr9FXkk/axrHe+FDuseeRDTzgCZiIkLiNslGj8DyhWMluDVqJ4d/rkSCSD0ZkvapriTFGgRJvGYHrSt3PsULJl2/tzvn7hwTJ13+iPurUD9sIWhjqaJfDaKt4ZHyBGAQzuNaK8LtZMDFDjD+9eK2z4RvP6lClesd9G4tmRYjr4xj652kD1fHPbVBsVWNbdYFUeWvY5fWITWmRhk7qn2zCu5VbubiUEyv8k5belDA0w8rLM/zFXZs=
  file:
    - "$TRAVIS_BUILD_DIR/$WP_THEME.zip"
    - "$TRAVIS_BUILD_DIR/$WP_THEME.zip.sha256"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: godaddy/wp-lyrical-theme
